version: "3.9"
services:
  api:
    image: python:3.10-slim-buster
    volumes:
      - .:/home/universe_backend
    ports:
      - 3333:3333

  db:
    image: mysql:8.0.33
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
