version: "3.9"
services:
  database:
    image: mysql:latest
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-data:/var/lib/mysql
    networks:
      - universe_net
    ports:
      - 22:3306

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: carlossandoval03/universe_backend:latest
    volumes:
      - .:/home/universe_backend
    ports:
      - 3333:3333
    depends_on:
      - database
    networks:
      - universe_net

networks:
  universe_net:
